# Site settings
title: Cecília Coelho
email: coelhomc@hsu-hh.de
description: Academic webpage of Cecília Coelho
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Cecília Coelho<br/>
  Researcher at Helmut-Schmidt University, Germany
  Invited Assistant Professor at Polythecnic Institute of Viana do Castelo, Portugal<br/>
  Member of the Centre of Mathematics of University of Minho, Portugal

location: >
  Helmut-Schmidt-Universität - Universität der Bundeswehr Hamburg<br/>
  Holstenhofweg 85<br/>
  22043 Hamburg, Germay<br/>
  

contact: >
  <a href="mailto:coelhomc@hsu-hh.de" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact me via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
  - name: research
  - name: software
  - name: teaching
  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
