# Site settings
title: AP Group
email: alberto.padovan@njit.edu
description: Alberto Padovan's research website at NJIT
baseurl: "/apgroup"
url: "https://albertopadovan.github.io"

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Alberto Padovan<br/>
  Assistant Professor<br/>
  Mechanical and Industrial Eng.<br/>
  New Jersey Institute of Technology

location: >
  New Jersey Institute of Technology<br/>
  200 Central Ave #204<br/>
  Newark, NJ 07114

contact: >
  Office: 262 Fenster Hall<br/>
  Phone: (973) 642-4244<br/>
  Email: alberto.padovan@njit.edu

# Pages shown in navbar
nav_pages:
  - name: team
  - name: publications
  - name: talks
  - name: software

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Padovan
  first_name: [Alberto]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month, day
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  # bibliography_list_attributes:
  #   reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
